import type { Platform } from '../../types.js'

interface AppConfigEnv {
  name: string
  android?: { packageName: string }
  ios?: { bundleId: string }
}

interface GenerateAppConfigParams {
  envs: AppConfigEnv[]
  outDir: string
  platform: Platform
}

export function generateAppConfigTs(params: GenerateAppConfigParams): string {
  const { envs, outDir, platform } = params

  const includeAndroid = platform === 'android' || platform === 'both'
  const includeIOS = platform === 'ios' || platform === 'both'

  const envEntries = envs
    .map((env) => {
      const androidLine =
        includeAndroid && env.android
          ? `    android: './${outDir}/${env.name}-${env.android.packageName}-google-services.json',`
          : null
      const iosLine =
        includeIOS && env.ios
          ? `    ios: './${outDir}/${env.name}-${env.ios.bundleId}-GoogleService-Info.plist',`
          : null
      const lines = [androidLine, iosLine].filter(Boolean).join('\n')
      return `  ${env.name}: {\n${lines}\n  },`
    })
    .join('\n')

  const androidSpread = includeAndroid
    ? `  android: {\n    ...(appJsonData.expo?.android as object | undefined),\n    googleServicesFile: firebaseFiles[env]?.android,\n  },`
    : null
  const iosSpread = includeIOS
    ? `  ios: {\n    ...(appJsonData.expo?.ios as object | undefined),\n    googleServicesFile: firebaseFiles[env]?.ios,\n  },`
    : null
  const platformSpreads = [androidSpread, iosSpread].filter(Boolean).join('\n')

  return `// Auto-generated by @cardor/rn-firebase-cli
// Commit this file. Do NOT commit your .env.* files.
import type { ExpoConfig } from 'expo/config'
import appJsonData from './app.json'

const env = (process.env.APP_ENV ?? '${envs[0]?.name ?? 'dev'}') as string

const firebaseFiles: Record<string, { android?: string; ios?: string }> = {
${envEntries}
}

const config = {
  ...appJsonData.expo,
${platformSpreads}
} as ExpoConfig

export default config
`
}
