import type { RNFConfig } from '../../types.js'

export function configTs(config: RNFConfig): string {
  return `// Auto-generated by @cardor/rn-firebase-cli — do not commit sensitive files
import type { RNFConfig } from '@cardor/rn-firebase-cli'

export default ${JSON.stringify(config, null, 2)} satisfies RNFConfig
`
}

export function configMjs(config: RNFConfig): string {
  return `// Auto-generated by @cardor/rn-firebase-cli — do not commit sensitive files

/** @type {import('@cardor/rn-firebase-cli').RNFConfig} */
export default ${JSON.stringify(config, null, 2)}
`
}

export function configCjs(config: RNFConfig): string {
  return `// Auto-generated by @cardor/rn-firebase-cli — do not commit sensitive files

/** @type {import('@cardor/rn-firebase-cli').RNFConfig} */
module.exports = ${JSON.stringify(config, null, 2)}
`
}

export interface FirebaseConfigParams {
  /** Unquoted JS expression to use for webClientId (e.g. process.env.EXPO_PUBLIC_FIREBASE_WEB_CLIENT_ID).
   *  When provided, the value is emitted as a raw expression in the object literal, not a JSON string.
   *  When undefined the webClientId property is omitted entirely. */
  webClientIdEnvRef?: string
  androidPackageName?: string
  iosBundleId?: string
}

function buildFirebaseConfigObject(params: FirebaseConfigParams): string {
  const lines: string[] = []

  if (params.webClientIdEnvRef !== undefined) {
    lines.push(`  webClientId: ${params.webClientIdEnvRef}`)
  }
  if (params.androidPackageName !== undefined) {
    lines.push(`  androidPackageName: ${JSON.stringify(params.androidPackageName)}`)
  }
  if (params.iosBundleId !== undefined) {
    lines.push(`  iosBundleId: ${JSON.stringify(params.iosBundleId)}`)
  }

  if (lines.length === 0) return '{}'
  return `{\n${lines.join(',\n')},\n}`
}

export function firebaseConfigTs(params: FirebaseConfigParams): string {
  return `// Auto-generated by @cardor/rn-firebase-cli — do not commit this file
export const FIREBASE_CONFIG = ${buildFirebaseConfigObject(params)}
`
}

export function firebaseConfigMjs(params: FirebaseConfigParams): string {
  return `// Auto-generated by @cardor/rn-firebase-cli — do not commit this file
export const FIREBASE_CONFIG = ${buildFirebaseConfigObject(params)}
`
}

export function firebaseConfigCjs(params: FirebaseConfigParams): string {
  return `// Auto-generated by @cardor/rn-firebase-cli — do not commit this file
const FIREBASE_CONFIG = ${buildFirebaseConfigObject(params)}
module.exports = { FIREBASE_CONFIG }
`
}
