import type { RNFConfig } from '../../types.js'

export function configTs(config: RNFConfig): string {
  return `// Auto-generated by @cardor/rn-firebase-cli — do not commit sensitive files
import type { RNFConfig } from '@cardor/rn-firebase-cli'

export default ${JSON.stringify(config, null, 2)} satisfies RNFConfig
`
}

export function configMjs(config: RNFConfig): string {
  return `// Auto-generated by @cardor/rn-firebase-cli — do not commit sensitive files

/** @type {import('@cardor/rn-firebase-cli').RNFConfig} */
export default ${JSON.stringify(config, null, 2)}
`
}

export function configCjs(config: RNFConfig): string {
  return `// Auto-generated by @cardor/rn-firebase-cli — do not commit sensitive files

/** @type {import('@cardor/rn-firebase-cli').RNFConfig} */
module.exports = ${JSON.stringify(config, null, 2)}
`
}

export function firebaseConfigTs(params: {
  webClientId?: string
  androidPackageName?: string
  iosBundleId?: string
}): string {
  return `// Auto-generated by @cardor/rn-firebase-cli — do not commit this file
export const FIREBASE_CONFIG = ${JSON.stringify(params, null, 2)}
`
}

export function firebaseConfigMjs(params: {
  webClientId?: string
  androidPackageName?: string
  iosBundleId?: string
}): string {
  return `// Auto-generated by @cardor/rn-firebase-cli — do not commit this file
export const FIREBASE_CONFIG = ${JSON.stringify(params, null, 2)}
`
}

export function firebaseConfigCjs(params: {
  webClientId?: string
  androidPackageName?: string
  iosBundleId?: string
}): string {
  return `// Auto-generated by @cardor/rn-firebase-cli — do not commit this file
const FIREBASE_CONFIG = ${JSON.stringify(params, null, 2)}
module.exports = { FIREBASE_CONFIG }
`
}
